spring:
  application:
    name: jwt-test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  accesExpiredMs: 36000000
  refreshExpiredMs: 864000000

logging:
  level:
    sql: debug
